version: '3.8'

volumes:
  postgres-data:
    external: false

networks:
  swaga-sber-network:
    driver: bridge

services:
  db:
    container_name: swaga-sber-postgres
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    networks:
      - swaga-sber-network

  app:
    container_name: sberhackathon-app
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=db;Username=user;Password=pass
    networks:
      - swaga-sber-network
