version: '3.8'

volumes:
  postgres-data:
    external: false

networks:
  swaga-sber-network:
    driver: bridge

services:
  db:
    container_name: swaga-sber-postgres
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    networks:
      - swaga-sber-network

  server:
    container_name: swaga-sber-server
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - swaga-sber-network